"""empty message

Revision ID: 198b52807527
Revises: 44eb8a10214a
Create Date: 2016-10-28 23:13:44.454009

"""

# revision identifiers, used by Alembic.
revision = '198b52807527'
down_revision = '44eb8a10214a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedulers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heatscheduler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('dow', sa.Integer(), nullable=True),
    sa.Column('thigh', sa.Integer(), nullable=True),
    sa.Column('tlow', sa.Integer(), nullable=True),
    sa.Column('scheduler_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scheduler_id'], ['schedulers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heatscheduler')
    op.drop_table('schedulers')
    ### end Alembic commands ###
