"""empty message

Revision ID: 21da47678b6
Revises: 500b56c30698
Create Date: 2016-10-29 19:54:14.384883

"""

# revision identifiers, used by Alembic.
revision = '21da47678b6'
down_revision = '500b56c30698'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
