"""empty message

Revision ID: 44eb8a10214a
Revises: 506127e1c859
Create Date: 2016-10-23 12:40:06.993919

"""

# revision identifiers, used by Alembic.
revision = '44eb8a10214a'
down_revision = '506127e1c859'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
