"""empty message

Revision ID: 500b56c30698
Revises: 3ebf8908cc44
Create Date: 2016-10-29 19:27:11.633760

"""

# revision identifiers, used by Alembic.
revision = '500b56c30698'
down_revision = '3ebf8908cc44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
