"""empty message

Revision ID: 506127e1c859
Revises: 33c15b049a1c
Create Date: 2016-10-22 22:59:09.579579

"""

# revision identifiers, used by Alembic.
revision = '506127e1c859'
down_revision = '33c15b049a1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('passwd', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
